export type RepertoireCategory = {
  id: string;
  title: string;
  songs: string[];
};

export const REPERTOIRE_CATEGORIES: RepertoireCategory[] = [
  {
    id: "chill-latin",
    title: "Chill vibing + Latin pop",
    songs: [
      "Fly As Me — Silk Sonic",
      "Espresso — Sabrina Carpenter",
      "Gettin Jiggy wit it — Will Smith",
      "Finesse — Cardi B",
      "Levitating — Dua Lipa",
      "Water — TYLA",
      "About Damn Time — Lizzo",
      "Let's Get it Started — Black Eyed Peas",
      "Wannabe — Spice Girls",
      "Party in the USA — Miley Cyrus",
      "Unwritten — Natasha Bedingfield",
      "Cuff It — Beyoncé",
      "Juice — Lizzo",
      "Dance the Night — Dua Lipa",
      "Uptown Funk — Bruno Mars",
      "24K Magic — Bruno Mars",
      "Don't Start Now — Dua Lipa",
      "Where Is My Husband — RAYE",
      "Last Friday Night — Katy Perry",
      "Domino — Jessie J",
    ],
  },
  {
    id: "funky-80s",
    title: "Funky + 80's",
    songs: [
      "Play That Funky Music — Wild Cherry",
      "Superstition — Stevie Wonder",
      "Never Too Much — Luther Vandross",
      "Stayin' Alive — Bee Gees",
      "Sex Machine — James Brown",
      "Get Down On It — Kool & The Gang",
      "Brick House — Commodores",
      "Hollaback Girl — Gwen Stefani",
      "Good Times + Lick It",
      "Le Freak — Chic",
      "I Wanna Be Your Lover — Prince",
      "Rock With You — Michael Jackson",
      "Don't Stop 'Til You Get Enough — Michael Jackson",
      "P.Y.T. — Michael Jackson",
      "I Wanna Dance With Somebody — Whitney Houston",
      "You Should Be Dancing — Bee Gees",
      "September — Earth, Wind & Fire",
      "Gimme Gimme — ABBA",
      "Dancing Queen — ABBA",
      "YMCA — Village People",
    ],
  },
  {
    id: "international",
    title: "International hits",
    songs: [
      "Moves Like Jagger — Maroon 5",
      "Starships — Nicki Minaj",
      "Right Round — Flo Rida",
      "Give Me Everything — Pitbull",
      "I Gotta Feeling — Black Eyed Peas",
      "Don't Stop Me Now — Queen",
    ],
  },
  {
    id: "rock-classic",
    title: "Rock & classic",
    songs: [
      "All the Small Things + First Date — Blink 182",
      "Basket Case — Green Day",
      "All Star + I'm a Believer — Smash Mouth",
      "Last Resort — Papa Roach",
      "Mr Brightside — The Killers",
    ],
  },
  {
    id: "drums-show",
    title: "Drums show",
    songs: [
      "Freed From Desire — Gala",
      "Pepas — Farruko",
      "Fireball — Pitbull",
      "Temperature — Sean Paul",
      "Don't Stop the Party — Pitbull",
    ],
  },
  {
    id: "hiphop-rnb",
    title: "Hip hop & R&B",
    songs: [
      "Hot in Herre — Nelly",
      "Yeah — Usher",
      "Crazy in Love — Beyoncé",
      "Get Busy — Sean Paul",
      "Hips Don't Lie — Shakira",
      "Tití Me Preguntó — Bad Bunny",
    ],
  },
  {
    id: "dj-selection",
    title: "DJ selection",
    songs: [
      "California Love — 2Pac",
      "Low — T-Pain",
      "Hotel Room Service — Pitbull",
      "Get Low — Lil Jon",
      "Thrift Shop — Macklemore",
      "This Is How We Do It — Montell Jordan",
      "Gold Digger — Jamie Foxx",
      "One Dance — Drake",
      "Get Ur Freak On — Missy Elliott",
    ],
  },
];
