export type RepertoireCategory = {
  id: string;
  title: string;
  songs: string[];
};

export const REPERTOIRE_CATEGORIES_ES: RepertoireCategory[] = [
  {
    id: "chill-latin-pop",
    title: "Chill Vibing + Latin Pop",
    songs: [
      "24K Magic — Bruno Mars",
      "Fly As Me — Silk Sonic",
      "Levitating — Dua Lipa",
      "About Damn Time — Lizzo",
      "Let's Get It Started — Black Eyed Peas",
      "Wannabe — Spice Girls",
      "Party in the USA — Miley Cyrus",
      "Unwritten — Natasha Bedingfield",
      "Cuff It — Beyoncé",
      "Dance the Night — Dua Lipa",
      "Uptown Funk — Bruno Mars",
      "Treasure — Bruno Mars",
      "Valerie — Amy Winehouse",
      "Blurred Lines — Robin Thicke",
      "Nochentera — Vicco",
      "Tacones Rojos — Sebastián Yatra",
      "Don't Start Now — Dua Lipa",
      "Shut Up and Dance — Walk the Moon",
    ],
  },
  {
    id: "funky-80s",
    title: "Funky + 80's",
    songs: [
      "Play That Funky Music — Wild Cherry",
      "Sex Machine — James Brown",
      "Brick House — Commodores",
      "Hollaback Girl — Gwen Stefani",
      "Good Times + Lick It",
      "Le Freak — Chic",
      "I Wanna Be Your Lover — Prince",
      "Rock With You — Michael Jackson",
      "Don't Stop 'Til You Get Enough — Michael Jackson",
      "I Wanna Dance With Somebody — Whitney Houston",
      "You Should Be Dancing — Bee Gees",
      "September — Earth, Wind & Fire",
      "Gimme Gimme — ABBA",
      "Dancing Queen — ABBA",
      "YMCA — Village People",
    ],
  },
  {
    id: "international",
    title: "International Hits",
    songs: [
      "Moves Like Jagger — Maroon 5",
      "Starships — Nicki Minaj",
      "Right Round — Flo Rida",
      "Give Me Everything — Pitbull",
      "I Gotta Feeling — Black Eyed Peas",
      "Music Sessions Vol.52 — Bizarrap & Quevedo",
    ],
  },
  {
    id: "reggaeton-latin",
    title: "Reggaetón / Latin Hits",
    songs: [
      "Vagabundo — Sebastián Yatra",
      "El Merengue — Manuel Turizo",
      "Limbo — Daddy Yankee",
      "Danza Kuduro — Don Omar",
      "Ella Me Levantó — Daddy Yankee (Svg Mix)",
      "Me Rehúso — Danny Ocean",
      "Tití Me Preguntó — Bad Bunny",
      "DTMF — Bad Bunny",
      "Atrévete-te-te — Calle 13 (Svg Mix)",
      "Como Te Atreves — Morat",
      "Me Has Invitado a Bailar — Dani Fernández",
      "Si Antes Te Hubiera Conocido — Karol G",
    ],
  },
  {
    id: "hits-nuevos-clasicos",
    title: "Hits Nuevos / Clásicos",
    songs: [
      "Sara Perché Ti Amo — DJ Márquez",
      "Princesas — Pereza",
      "Tanto Que Darte — Nena Daconte",
      "Coti x Coti (remix) — The Tyets",
      "Revolución Sexual — La Casa Azul",
      "La La Love — El Fin del Mundo",
      "Freed From Desire — Gala",
      "Zapatillas — El Canto del Loco",
      "Física o Química — Despistaos",
      "La Mujer de Verde — Izal",
      "Marina Sta Morena — Figa Flawas",
      "Viva La Vida — Coldplay",
      "La Travesía — Juan Luis Guerra",
      "Besos — El Canto del Loco",
    ],
  },
];
